name: Cypress Testing

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./web

jobs:
  cypress-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress testing
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start

