name: Cypress Testing

on:
  workflow_dispatch:

jobs:
  cypress-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress testing
        uses: cypress-io/github-action@v2
        with:
          headless: true
          project: ./web
          build: npm run build
          start: npm start

