name: Cypress Testing

on:
  workflow_dispatch:

jobs:
  cypress-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cypress testing
        uses: cypress-io/github-action@v2
        with:
          headless: true
          working-directory: ./web
          build: npm run build
          start: npm start

